apiVersion: v1
kind: Service
metadata:
  name: {{ include "snorby.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snorby.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      {{- if .Values.service.http.nodeport }}
      nodePort: {{ .Values.service.http.nodeport }}
      {{- end }}
      targetPort: {{ .Values.service.http.port }}
      protocol: {{ .Values.service.http.protocol }}
      name: http
  selector:
    {{- include "snorby.selectorLabels" . | nindent 4 }}
