# Default values for snorby.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global: {}

replicaCount: 1

image:
  repository: polinux/snorby
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

dbenv:
  hostname: "{{ .Release.Name }}-mysql.{{ .Release.Namespace }}"
  username: "root"
  password: "test"

cmdstr: |
  yum update -y nss curl libcurl
  sleep 5
  /bootstrap.sh

service:
  type: NodePort
  http:
    protocol: TCP
    port: 3000
    nodeport: 31333

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 2Gi

nodeSelector: {}

tolerations: []

affinity: {}

dev:
  enabled: false

