apiVersion: v1
kind: Service
metadata:
  name: {{ include "snortsft.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snortsft.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.service.nodeport }}
      nodePort: {{ .Values.service.nodeport }}
      {{- end }}
      targetPort: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "snortsft.selectorLabels" . | nindent 4 }}
